### ISSUE TITLE
How do I import into my Library

### ISSUE THREAD

**Issue by jrock2004** [impulse/tailwindcss-figma-kit#1]
Sorry, I am new to Figma but I am curios how can I use the library in my projects

**Comment by impulse** [comment]
I've already answered on [Discord](http://tailwindcss.com/discord) but I came across team libraries. Not sure how they exactly work yet but I've created a dedicated team for this project. Can you try opening the project [https://www.figma.com/file/NukLikyVAtxNnsBDWuOYrmED/TailwindCSS-Figma?node-id=0%3A1](here) and use it in one of your own drafts?

**Comment by jrock2004** [comment]
Yeah, I was looking in the wrong place. I went into settings and tried to add it there. If I open a project I can add it there so I am good now

**Comment by impulse** [comment]
Cool! Closing this then
