### ISSUE TITLE
All colour styles are prefixed with `default/` 

### ISSUE THREAD

**Issue by allymparker** [impulse/tailwindcss-figma-kit#6]
When I import my config using the plugin, I need to add "default" as the prefix in order to overwrite the built-in styles.  I'd prefer these to not have this prefix - this will help people using the plugin to overwrite the styles in the .fig.

The font styles don't include `default` as a prefix.

**Comment by impulse** [comment]
@allymparker good point, I removed the default prefix and also added tailwindui colors.
